// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:smarttrip/domain/models/trip.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TripAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TripAdapter());
  }
}
